# Generated by Django 5.0.14 on 2025-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0002_subscription_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="permissions",
            field=models.ManyToManyField(
                limit_choices_to={
                    "codename__in": ["basic", "basic_ai", "pro", "advanced"],
                    "content_type__app_label": "subscriptions",
                },
                to="auth.permission",
            ),
        ),
    ]
