# Generated by Django 5.2.3 on 2025-06-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Visit",
            new_name="PageVisit",
        ),
    ]
